name: Check Winning
on:
  schedule:
    - cron: 0 13 * * 6 # every Saturday on 10:00 PM (KST)
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Check Winning
    steps:  

      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Run Scripts
        run: make check
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COUNT: ${{ secrets.COUNT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}